apiVersion: v1
kind: Service
metadata:
  name: "doctor-api"
  labels:
    {{- include "doctor-api.labels" . | nindent 4 }}
spec:
  spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

    - port: 443
      targetPort: https
      protocol: TCP
      name: https

  selector:
    {{- include "doctor-api.selectorLabels" . | nindent 4 }}
