apiVersion: v1
kind: Service
metadata:
  name: "doctor-api"
  labels:
    {{- include "doctor-api.labels" . | nindent 4 }}
spec:
  spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    #- port: 2022
    #  targetPort: http
    #  protocol: TCP
    #  name: http

    #- port: 7923
    #  targetPort: 7923
    #  protocol: TCP
    #  name: tcp-7923

    #- port: 9899
    #  targetPort: 9899
    #  protocol: TCP
    #  name: tcp-9899

  selector:
    {{- include "doctor-api.selectorLabels" . | nindent 4 }}
