apiVersion: apps/v1
kind: Deployment
metadata:
  name: "insurtech"
  labels:
    {{- include "insurtech.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "insurtech.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "insurtech.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "insurtech"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
          - name: PATH
            value: {{ .Values.PATH }}
          - name: ASPNETCORE_URLS
            value: {{ .Values.ASPNETCORE_URLS }}
          - name: DOTNET_RUNNING_IN_CONTAINER
            value: {{ .Values.DOTNET_RUNNING_IN_CONTAINER }}
          - name: DOTNET_VERSION
            value: {{ .Values.DOTNET_VERSION }}
          - name: ASPNET_VERSION
            value: {{ .Values.ASPNET_VERSION }}
          - name: Logging__Console__FormatterName
            value: {{ .Values.Logging__Console__FormatterName }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.ASPNETCORE_ENVIRONMENT }}
            
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
