apiVersion: v1
kind: Service
metadata:
  name: "aicareui-api"
  labels:
    {{- include "aicareui-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "aicareui-api.selectorLabels" . | nindent 4 }}
