apiVersion: v1
kind: Service
metadata:
  name: "pgadmin"
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pgadmin.selectorLabels" . | nindent 4 }}
