apiVersion: v1
kind: Service
metadata:
  name: "userportal"
  labels:
    {{- include "userportal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "userportal.selectorLabels" . | nindent 4 }}
